services:
  postgres:
    image: postgres:16-bookworm
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_HOST:-127.0.0.1}:${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  minio:
    image: bitnami/minio:2024-debian-12
    volumes:
      - minio-data:/data
    ports:
      - ${MINIO_HOST:-127.0.0.1}:${MINIO_PORT:-9000}:9000
      - ${MINIO_UI_HOST:-127.0.0.1}:${MINIO_UI_PORT:-9001}:9001
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
      MINIO_DEFAULT_BUCKETS: bucket

  minio-client:
    profiles:
      - optional
    image: bitnami/minio-client:2024-debian-12
    environment:
      MINIO_SERVER_HOST: minio
      MINIO_SERVER_ACCESS_KEY: user
      MINIO_SERVER_SECRET_KEY: password
    configs:
      - source: minio-client-config
        target: /.mc/config.json

configs:
  minio-client-config:
    content: |
      {
        "version": "10",
        "aliases": {
          "minio": {
            "url": "http://minio:9000",
            "accessKey": "user",
            "secretKey": "password",
            "api": "S3v4",
            "path": "auto"
          },
          "play": {
            "url": "https://play.min.io",
            "accessKey": "Q3AM3UQ867SPQQA43P2F",
            "secretKey": "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
            "api": "S3v4",
            "path": "auto"
          }
        }
      }

volumes:
  postgres-data:
  minio-data:
